name: log github events

on:
  push:
    branches: [main, master]
  pull_request:
    types: [opened, closed]
    branches: [main, master]

jobs:
  log:
    runs-on: ubuntu-latest

    env:
      COMMIT_LOG_API: ${{ secrets.COMMIT_LOG_API }}
      GITHUB_LOGIN: ${{ github.actor }} # github login also available in github.triggering_actor, github.event.sender.login
      COMMITS: ${{ toJson(github.event.commits) }}
      REPOSITORY_URL: ${{ github.repositoryUrl }}
      EVENT_TYPE: ${{ github.event_name }}
      EVENT_ACTION: ${{ github.event.action }}
      PR_MERGED: ${{ github.event.pull_request.merged }}
      PR_CREATED_AT: ${{ github.event.pull_request.created_at }}
      PR_CLOSED_AT: ${{ github.event.pull_request.closed_at }}

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # this is important so git fetches all history.. the actions/checkout by default fetches all history as one commit which throws off stats

    - uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    # Optional Node.js setup to avoid future warnings
    - name: Set up Node.js (optional)
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --dev
        pipenv --version
        pipenv graph  # Outputs dependency tree for debugging

    - name: Log pull request opened
      if: github.event_name == 'pull_request' && github.event.action == 'opened'
      run: |
        pipenv run gitcommitlogger -r ${REPOSITORY_URL} -u ${GITHUB_LOGIN} --t ${PR_CREATED_AT} -o commit_stats.csv -v ${COMMIT_LOG_API}

    - name: Log pull request closed and merged
      if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
      run: |
        pipenv run gitcommitlogger -r ${REPOSITORY_URL} -u ${GITHUB_LOGIN} --t ${PR_CLOSED_AT} --merged -o commit_stats.csv -v ${COMMIT_LOG_API}

    - name: Log pull request closed without merge
      if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == false
      run: |
        pipenv run gitcommitlogger -r ${REPOSITORY_URL} -u ${GITHUB_LOGIN} --t ${PR_CLOSED_AT} -o commit_stats.csv -v ${COMMIT_LOG_API}

    - name: Log push
      if: github.event_name == 'push'
      run: |
        echo $COMMITS > commits.json
        cat commits.json
        pipenv run gitcommitlogger -r ${REPOSITORY_URL} -t ${EVENT_TYPE} -i commits.json -o commit_stats.csv -v ${COMMIT_LOG_API}

