name: log github events

on:
  pull_request:
    types: [opened, closed]
    branches: [main, master]

jobs:
  log:
    runs-on: ubuntu-latest

    env:
      COMMIT_LOG_API: ${{ secrets.COMMIT_LOG_API }}
      GITHUB_LOGIN: ${{ github.actor }}
      REPOSITORY_URL: ${{ github.repositoryUrl }}
      PR_CLOSED_AT: ${{ github.event.pull_request.closed_at }}

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Debug Info
      run: |
        echo "Repository URL: ${REPOSITORY_URL}"
        echo "GitHub Login: ${GITHUB_LOGIN}"
        echo "Commit Log API: ${COMMIT_LOG_API}"
        echo "PR Closed At: ${PR_CLOSED_AT}"

    - name: Log pull request closed and merged
      if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
      run: |
        if [ -z "${REPOSITORY_URL}" ]; then
          echo "Error: REPOSITORY_URL is empty."
          exit 1
        fi
        pipenv run gitcommitlogger -r ${REPOSITORY_URL} -u ${GITHUB_LOGIN} --t ${PR_CLOSED_AT} --merged -o commit_stats.csv -v ${COMMIT_LOG_API}


